name: CD
on: 
  push:
    branches:
      - main
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read Config
        id: config
        run: |
          echo "site_version=$(cat devops_course/cicd_workshop/app/site/version)" >> "$GITHUB_OUTPUT"
          echo "api_version=$(cat devops_course/cicd_workshop/app/api/version)" >> "$GITHUB_OUTPUT"

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: devops_course/cicd_workshop/app/api
          push: true
          tags: itswatthachai/devops-quickstart-api:${{steps.config.outputs.api_version}}

      - name: Build and push Site
        uses: docker/build-push-action@v5
        with:
          context: devops_course/cicd_workshop/app/site
          push: true
          tags: itswatthachai/devops-quickstart-site:${{steps.config.outputs.site_version}}