name: CD_ENV
on:
  push:
    branches:
      - main
env:
  TF_CLI_CONFIG_FILE: "./.terraformrc"
  TF_WORKING_DIR: "devops_course/cicd_workshop/env"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Setup Terraform Config File
        id: terraform-config
        run: |-
          # Create Terraform CLI config file in the HOME directory where Terraform looks for it by default
          cat > $HOME/.terraformrc <<EOF
          credentials "app.terraform.io" {
            token = "${{ secrets.TF_API_TOKEN }}"
          }
          EOF
          
          # Set DigitalOcean token as environment variable for Terraform to use
          echo "TF_VAR_do_token=${{ secrets.DO_TOKEN }}" >> $GITHUB_ENV

      - name: Debug .terraformrc File
        run: |
          cat .terraformrc || echo ".terraformrc file not found!"

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform apply -auto-approve -no-color

      - name: Terraform Output
        id: output
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform output | sed -r 's/.+"([0-9,\.]+)"/ip=\1/' >> "$GITHUB_OUTPUT"

      - name: Check SSH Port Alive
        id: check-ssh-alive
        run: |
          while ! nc -z ${{ steps.output.outputs.ip }} 22; do   
            sleep 1
            echo "port not response"
          done

      - name: Read Config
        id: config
        run: |
          docker_content=$(cat ${{ env.TF_WORKING_DIR }}/docker-compose.yml)
          echo "docker_content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$docker_content" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          kong_content=$(cat ${{ env.TF_WORKING_DIR }}/kong/kong.yml)
          echo "kong_content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$kong_content" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Deploy
        id: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.output.outputs.ip }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose down

            rm -f ./docker-compose.yml

            mkdir -p ./kong
            cat > ./kong/kong.yml <<EOF
            ${{steps.config.outputs.kong_content}}
            EOF
            cat > ./docker-compose.yml <<EOF
            ${{steps.config.outputs.docker_content}}
            EOF

            docker compose up -d