name: CI

on:
  push:
    paths:
      - 'devops_course/cicd_workshop/app/**'
  pull_request:
    paths:
      - 'devops_course/cicd_workshop/app/**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install site dependencies
        run: cd devops_course/cicd_workshop/app/site && npm ci --force

      - name: Test site
        run: cd devops_course/cicd_workshop/app/site && npm test

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install API dependencies
        run: cd devops_course/cicd_workshop/app/api && go mod download

      - name: Test API
        run: cd devops_course/cicd_workshop/app/api && go test -v ./...
